module.exports = [
    {
      id: "1",
      name: "Tuscan Chicken Skillet",
      directions:"Cook the fettuccine according to package directions; drain. Meanwhile, put the bacon in a large, cold skillet, then cook over medium-high heat, until crispy, about 8 minutes; transfer to a plate with a slotted spoon. Sprinkle the chicken lightly with salt and pepper and add to the skillet in a single layer. Let cook, undisturbed, until golden brown on the underside. Continue to cook, stirring occasionally, until cooked through. Transfer to the plate with the bacon. Reduce the heat to medium and add the garlic, stirring, until fragrant, about 30 seconds. Add the tomatoes and cream and bring to a simmer, then add the spinach and stir until just wilted. Add the bacon, chicken, fettuccine and Parmesan and toss with tongs until well coated; season to taste with salt and pepper. Sprinkle with basil and serve.",
      ingredient1:"12 ounces fettuccine",
      ingredient2:"4 slices bacon, chopped",
      ingredient3:"1 pound chicken tenders, cut into 1-inch pieces",
      ingredient4:"2 cloves garlic, minced",
      ingredient5:"4 plum tomatoes, chopped",
      ingredient6:"1 cup heavy cream",
      ingredient7:"5 ounces baby spinach",
      ingredient8:"3/4 cup grated Parmesan",
      product_img:"https://food.fnr.sndimg.com/content/dam/images/food/fullset/2018/9/26/0/FNK_Tuscan-Chicken-Skillet_H2_s4x3.jpg.rend.hgtvcom.826.620.suffix/1537973085542.jpeg"
    },
    {
        id: "2",
        name: "Chicken Tinga Tacos",
        directions:"Heat the oil in a large saute pan over medium-high heat. Add the onions and saute until they begin to soften, about 3 minutes. Add the chipotles, garlic, cumin, salt and cayenne and saute until fragrant, about 1 minute. Stir in the tomatoes and stock and cook until they begin to simmer, about 2 minutes. Turn off the heat and carefully ladle the sauce into a heat-safe blender. Puree until smooth. Pour the sauce back into the pan over medium heat and add the chicken, stirring to incorporate the chicken into the sauce. Cook until the sauce has thickened, about 5 minutes. Serve with tortillas and desired toppings.",
        ingredient1:"1 small yellow onion, chopped",
        ingredient2:"2 chipotles in adobo, finely chopped",
        ingredient3:"1 tablespoon ground cumin",
        ingredient4:"1/2 teaspoon cayenne pepper",
        ingredient5:"One 10-ounce can diced tomatoes and green chiles",
        ingredient6:"1 cup chicken stock",
        ingredient7:"51 rotisserie chicken, shredded",
        ingredient8:"Charred corn tortillas, for serving",
        product_img:"https://food.fnr.sndimg.com/content/dam/images/food/fullset/2019/6/18/0/VB909_Chicken-Tinga-Tacos_s4x3.jpg.rend.hgtvcom.826.620.suffix/1560899449769.jpeg"
      },
      {
        id: "3",
        name: "Oven-Baked Salmon",
        directions:"Preheat the oven to 450 degrees F. Season salmon with salt and pepper. Place salmon, skin side down, on a non-stick baking sheet or in a non-stick pan with an oven-proof handle. Bake until salmon is cooked through, about 12 to 15 minutes. Serve with the Toasted Almond Parsley Salad and squash, if desired.",
        ingredient1:"12 ounce salmon fillet, cut into 4 pieces",
        ingredient2:"Coarse-grained salt",
        ingredient3:"Freshly ground black pepper",
        ingredient4:"Toasted Almond Parsley Salsa, for serving",
        ingredient5:"Extra-virgin olive oil",
        ingredient6:"1 cup fresh flat-leaf parsley",
        ingredient7:"1 shallot",
        ingredient8:"Baked squash, for serving, optional",
        product_img:"https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/7/26/1/CN1B01_oven-baked-salmon_s4x3.jpg.rend.hgtvcom.1280.720.suffix/1382545141944.jpeg"
      },
      {
        id: "4",
        name: "Balsamic Roast Pork Tenderloins",
        directions:"Preheat oven to 500 degrees F. Trim silver skin or connective tissue off tenderloins with a very sharp thin knife. Place tender loins on a nonstick cookie sheet with a rim. Coat tenderloins in a few tablespoons of balsamic vinegar, rubbing vinegar into meat. Drizzle tenderloins with extra-virgin olive oil, just enough to coat. Cut small slits into meat and disperse chunks of cracked garlic cloves into meat. Combine steak seasoning blend or coarse salt and pepper with rosemary and thyme and rub meat with blend. Roast in hot oven 20 minutes.",
        ingredient1:"4 1/2 pounds pork tenderloins",
        ingredient2:"4 tablespoons balsamic vinegar",
        ingredient3:"4 tablespoons extra-virgin olive oil",
        ingredient4:"8 cloves garlic, cracked",
        ingredient5:"Steak seasoning blend",
        ingredient6:"4 sprigs fresh rosemary leaves stripped and finely chopped",
        ingredient7:"Coarse salt and black pepper",
        ingredient8:"4 sprigs fresh thyme, leaves stripped and finely chopped",
        product_img:"https://food.fnr.sndimg.com/content/dam/images/food/fullset/2003/10/16/4/tm1b27_pork_tenderloins3.jpg.rend.hgtvcom.1280.720.suffix/1431255253080.jpeg"
      },
      {
        id: "5",
        name: "Cauliflower Parmesan",
        directions:"Working with the larger pieces first, add the cauliflower to the flour and turn to coat. Shake off the excess, then dip in the egg to coat. Let the excess egg drip off, then coat thoroughly in the panko. Fry the cauliflower in batches to avoid overcrowding, turning once, until golden brown on both sides, 6 to 8 minutes total. Transfer to the lined plate to drain and sprinkle with salt. Spread 1 cup marinara sauce on the bottom of a 9-by-13-inch baking dish. Arrange the fried cauliflower on top, then spoon 1 cup of the sauce on top of the cauliflower. Arrange the mozzarella over the sauce, then spoon the remaining 1/2 cup marinara over the top. Sprinkle with the Parmesan and bake. ",
        ingredient1:"1 medium head cauliflower",
        ingredient2:"1 cup all-purpose flour",
        ingredient3:"3 large eggs, beaten",
        ingredient4:"2 cups panko breadcrumbs",
        ingredient5:"About 1 cup olive oil",
        ingredient6:"2 1/2 cups marinara sauce, from a 24-ounce jar",
        ingredient7:"1/2 pound fresh mozzarella, thinly sliced",
        ingredient8:"1/3 cup grated Parmesan",
        product_img:"https://food.fnr.sndimg.com/content/dam/images/food/fullset/2018/9/26/0/FNK_Cauliflower-Parmesan_H2_s4x3.jpg.rend.hgtvcom.826.620.suffix/1537973100194.jpeg"
      },
      {
        id: "6",
        name: "Instant Pot Mac and Cheese",
        directions:"Combine the macaroni, 4 cups water and 1 tablespoon salt in a 6- or 8-quart Instant Pot® multi-cooker (see Cook's Note). Follow the manufacturer's guide for locking the lid and preparing to cook. Set to pressure cook on high for 4 minutes. After the pressure cook cycle is complete follow the manufacturer's guide for quick release and wait until the cycle is complete. Being careful of any remaining steam, unlock and remove the lid and switch to the low saute setting. Stir in the evaporated milk, butter and 1/4 cup water. Then add the Cheddar, a little at time, while constantly stirring, until the cheese is completely melted. Serve hot.",
        ingredient1:"1 pound elbow macaroni",
        ingredient2:"Kosher salt ",
        ingredient3:"One 12-ounce can evaporated milk",
        ingredient4:"3 tablespoons unsalted butter",
        ingredient5:"About 1 cup olive oil",
        ingredient6:"3 cups shredded mild or medium Cheddar  ",
        ingredient7:"Pepper seasoning",
        ingredient8:"1/3 cup grated Parmesan",
        product_img:"https://food.fnr.sndimg.com/content/dam/images/food/fullset/2017/2/28/0/FNK_Instapot-Mac-and-Cheese-H-0046_s4x3.jpg.rend.hgtvcom.1280.720.suffix/1488313700975.jpeg"
      },
      {
        id: "7",
        name: "Lentil Soup",
        directions:"Place the olive oil into a large 6-quart Dutch oven and set over medium heat. Once hot, add the onion, carrot, celery and salt and sweat until the onions are translucent, approximately 6 to 7 minutes. Add the lentils, tomatoes, broth, coriander, cumin and grains of paradise and stir to combine. Increase the heat to high and bring just to a boil. Reduce the heat to low, cover and cook at a low simmer until the lentils are tender, approximately 35 to 40 minutes. Using a stick blender, puree to your preferred consistency. Serve immediately.",
        ingredient1:"1 cup finely chopped onion",
        ingredient2:"1/2 cup finely chopped carrot",
        ingredient3:"1/2 cup finely chopped celery",
        ingredient4:"1 pound lentils, picked and rinsed",
        ingredient5:"1 cup peeled and chopped tomatoes",
        ingredient6:"2 quarts chicken or vegetable broth",
        ingredient7:"1/2 teaspoon freshly ground coriander and cumin",
        ingredient8:"1/2 teaspoon freshly ground grains of paradise",
        product_img:"https://food.fnr.sndimg.com/content/dam/images/food/fullset/2007/1/19/0/ea1015_soup1.jpg.rend.hgtvcom.1280.720.suffix/1382538506113.jpeg"
      },
      {
        id: "8",
        name: "Lemon-Garlic Shrimp and Grits",
        directions:"Bring 3 cups of water to a boil in a medium saucepan over high heat, covered. Uncover and slowly whisk in the grits, 1 teaspoon salt and 1/2 teaspoon pepper. Reduce the heat to medium low and cook, stirring occasionally, until thickened, about 5 minutes. Stir in the Parmesan and 1 tablespoon butter. Remove from the heat and season with salt and pepper. Cover to keep warm. Meanwhile, season the shrimp with salt and pepper. Melt the remaining 2 tablespoons butter in a large skillet over medium-high heat. Add the shrimp, garlic and cayenne, if using, and cook, tossing, until the shrimp are pink, 3 to 4 minutes. Remove from the heat and add 2 tablespoons water, the lemon juice and parsley; stir to coat the shrimp with the sauce and season with salt and pepper.",
        ingredient1:"3/4 cup instant grits",
        ingredient2:"Kosher salt and freshly ground black pepper",
        ingredient3:"1/4 cup grated Parmesan cheese",
        ingredient4:"3 tablespoons unsalted butter",
        ingredient5:"1 1/4 pounds medium shrimp, peeled and deveined, tails intact",
        ingredient6:"2 large cloves garlic, minced",
        ingredient7:"Juice of 1/2 lemon, plus wedges for serving",
        ingredient8:"2 tablespoons roughly chopped fresh parsley",
        product_img:"https://food.fnr.sndimg.com/content/dam/images/food/fullset/2010/11/1/1/FNM_120110-WN-Dinners-021_s4x3.jpg.rend.hgtvcom.1280.720.suffix/1382539568110.jpeg"
      }
]